<?php
use App\Models\Service;

$packages = [
    [
        'title' => 'Golden Triangle Tour Package',
        'slug' => 'golden-triangle-tour-package',
        'feature_image' => '',
        'duration' => '6 Nights / 7 Days',
        'amenities' => json_encode(['AC Cab', 'Guide', 'Hotel', 'Meals']),
        'highlights' => 'Delhi, Agra, Jaipur sightseeing',
        'itinerary' => 'Day 1: Delhi arrival. Day 2: Delhi sightseeing. Day 3: Agra visit. Day 4: Jaipur travel. Day 5: Jaipur sightseeing. Day 6: Return to Delhi.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, entry fees',
        'more_contents' => 'Experience the best of North India with our Golden Triangle Tour Package. Explore historical monuments, vibrant markets, and local cuisine.',
        'description' => 'The Golden Triangle Tour Package covers Delhi, Agra, and Jaipur, offering a unique blend of history, culture, and architecture. Enjoy guided tours, comfortable stays, and seamless travel for an unforgettable experience.',
        'is_active' => true,
        'meta_title' => 'Golden Triangle Tour Package',
        'meta_description' => 'Explore Delhi, Agra, and Jaipur with our Golden Triangle Tour Package. Best price, top amenities, and expert guides.',
        'meta_keywords' => 'golden triangle, tour package, delhi, agra, jaipur',
        'meta_canonical' => '',
        'offer' => '10% off for early bookings'
    ],
    [
        'title' => 'Golden Triangle with Ranthambore Tour Package',
        'slug' => 'golden-triangle-with-ranthambore-tour-package',
        'feature_image' => '',
        'duration' => '7 Nights / 8 Days',
        'amenities' => json_encode(['AC Cab', 'Guide', 'Hotel', 'Meals', 'Safari']),
        'highlights' => 'Delhi, Agra, Jaipur, Ranthambore',
        'itinerary' => 'Day 1: Delhi arrival. Day 2: Delhi sightseeing. Day 3: Agra visit. Day 4: Ranthambore safari. Day 5: Jaipur travel. Day 6: Jaipur sightseeing. Day 7: Return to Delhi.',
        'included' => 'Accommodation, transport, breakfast, safari, sightseeing',
        'excluded' => 'Lunch, personal expenses, entry fees',
        'more_contents' => 'Explore the wild side of Rajasthan with Ranthambore safari added to the classic Golden Triangle route.',
        'description' => 'This package combines the Golden Triangle with an adventurous Ranthambore safari. Enjoy wildlife, history, and culture in one trip.',
        'is_active' => true,
        'meta_title' => 'Golden Triangle with Ranthambore Tour Package',
        'meta_description' => 'Golden Triangle plus Ranthambore safari. Best price, top amenities, and expert guides.',
        'meta_keywords' => 'golden triangle, ranthambore, safari, tour package',
        'meta_canonical' => '',
        'offer' => 'Free safari upgrade'
    ],
    [
        'title' => 'Golden Triangle with Udaipur Tour Package',
        'slug' => 'golden-triangle-with-udaipur-tour-package',
        'feature_image' => '',
        'duration' => '8 Nights / 9 Days',
        'amenities' => json_encode(['AC Cab', 'Guide', 'Hotel', 'Meals']),
        'highlights' => 'Delhi, Agra, Jaipur, Udaipur',
        'itinerary' => 'Day 1: Delhi arrival. Day 2: Delhi sightseeing. Day 3: Agra visit. Day 4: Jaipur travel. Day 5: Jaipur sightseeing. Day 6: Udaipur travel. Day 7: Udaipur sightseeing. Day 8: Return to Delhi.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, entry fees',
        'more_contents' => 'Add the city of lakes, Udaipur, to your Golden Triangle journey for a royal experience.',
        'description' => 'Golden Triangle with Udaipur offers a blend of history, culture, and scenic beauty. Enjoy palaces, lakes, and vibrant markets.',
        'is_active' => true,
        'meta_title' => 'Golden Triangle with Udaipur Tour Package',
        'meta_description' => 'Golden Triangle plus Udaipur. Best price, top amenities, and expert guides.',
        'meta_keywords' => 'golden triangle, udaipur, tour package',
        'meta_canonical' => '',
        'offer' => 'Complimentary boat ride'
    ],
    [
        'title' => 'Golden Triangle with Varanasi and Khajuraho Tour Package',
        'slug' => 'golden-triangle-with-varanasi-and-khajuraho-tour-package',
        'feature_image' => '',
        'duration' => '10 Nights / 11 Days',
        'amenities' => json_encode(['AC Cab', 'Guide', 'Hotel', 'Meals']),
        'highlights' => 'Delhi, Agra, Jaipur, Varanasi, Khajuraho',
        'itinerary' => 'Day 1: Delhi arrival. Day 2: Delhi sightseeing. Day 3: Agra visit. Day 4: Jaipur travel. Day 5: Jaipur sightseeing. Day 6: Varanasi travel. Day 7: Varanasi sightseeing. Day 8: Khajuraho travel. Day 9: Khajuraho sightseeing. Day 10: Return to Delhi.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, entry fees',
        'more_contents' => 'Spiritual and historical journey through India’s most iconic cities.',
        'description' => 'This package covers the Golden Triangle with Varanasi and Khajuraho, offering spiritual, historical, and cultural experiences.',
        'is_active' => true,
        'meta_title' => 'Golden Triangle with Varanasi and Khajuraho Tour Package',
        'meta_description' => 'Golden Triangle plus Varanasi and Khajuraho. Best price, top amenities, and expert guides.',
        'meta_keywords' => 'golden triangle, varanasi, khajuraho, tour package',
        'meta_canonical' => '',
        'offer' => 'Free temple tour'
    ],
    [
        'title' => 'Golden Triangle Tour with Varanasi Tour Package',
        'slug' => 'golden-triangle-tour-with-varanasi-tour-package',
        'feature_image' => '',
        'duration' => '9 Nights / 10 Days',
        'amenities' => json_encode(['AC Cab', 'Guide', 'Hotel', 'Meals']),
        'highlights' => 'Delhi, Agra, Jaipur, Varanasi',
        'itinerary' => 'Day 1: Delhi arrival. Day 2: Delhi sightseeing. Day 3: Agra visit. Day 4: Jaipur travel. Day 5: Jaipur sightseeing. Day 6: Varanasi travel. Day 7: Varanasi sightseeing. Day 8: Return to Delhi.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, entry fees',
        'more_contents' => 'Experience the spiritual side of India with Varanasi added to the Golden Triangle.',
        'description' => 'Golden Triangle Tour with Varanasi offers a spiritual and cultural journey through India’s most famous cities.',
        'is_active' => true,
        'meta_title' => 'Golden Triangle Tour with Varanasi Tour Package',
        'meta_description' => 'Golden Triangle plus Varanasi. Best price, top amenities, and expert guides.',
        'meta_keywords' => 'golden triangle, varanasi, tour package',
        'meta_canonical' => '',
        'offer' => 'Free Ganga Aarti experience'
    ],
    [
        'title' => 'Manali Tour Package',
        'slug' => 'manali-tour-package',
        'feature_image' => '',
        'duration' => '4 Nights / 5 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Manali, Solang Valley, Rohtang Pass',
        'itinerary' => 'Day 1: Arrival in Manali. Day 2: Local sightseeing. Day 3: Solang Valley adventure. Day 4: Rohtang Pass excursion. Day 5: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Discover the beauty of Himachal Pradesh with our Manali Tour Package. Enjoy snow-capped mountains, adventure sports, and serene landscapes.',
        'description' => 'Manali Tour Package offers a refreshing escape to the hills. Experience adventure, relaxation, and local culture with our expertly curated itinerary and comfortable arrangements.',
        'is_active' => true,
        'meta_title' => 'Manali Tour Package',
        'meta_description' => 'Book Manali Tour Package for a memorable trip to Himachal Pradesh. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'manali, tour package, himachal, solang valley, rohtang pass',
        'meta_canonical' => '',
        'offer' => 'Flat Rs. 1000 off for couples'
    ],
    [
        'title' => 'Shimla Tour Package',
        'slug' => 'shimla-tour-package',
        'feature_image' => '',
        'duration' => '3 Nights / 4 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Shimla, Kufri, Mall Road',
        'itinerary' => 'Day 1: Arrival in Shimla. Day 2: Kufri excursion. Day 3: Mall Road sightseeing. Day 4: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Enjoy the cool climate and scenic beauty of Shimla with our package.',
        'description' => 'Shimla Tour Package is perfect for a quick getaway to the hills. Explore local attractions, enjoy comfortable stays, and relax in nature.',
        'is_active' => true,
        'meta_title' => 'Shimla Tour Package',
        'meta_description' => 'Book Shimla Tour Package for a memorable trip to Himachal Pradesh. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'shimla, tour package, himachal, kufri, mall road',
        'meta_canonical' => '',
        'offer' => 'Early bird discount'
    ],
    [
        'title' => 'Kashmir Tour Package',
        'slug' => 'kashmir-tour-package',
        'feature_image' => '',
        'duration' => '5 Nights / 6 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Srinagar, Gulmarg, Pahalgam',
        'itinerary' => 'Day 1: Arrival in Srinagar. Day 2: Gulmarg excursion. Day 3: Pahalgam sightseeing. Day 4: Srinagar local tour. Day 5: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Experience the paradise of Kashmir with our exclusive package.',
        'description' => 'Kashmir Tour Package offers breathtaking views, cultural experiences, and comfortable stays. Perfect for families and couples.',
        'is_active' => true,
        'meta_title' => 'Kashmir Tour Package',
        'meta_description' => 'Book Kashmir Tour Package for a memorable trip to the valley. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'kashmir, tour package, srinagar, gulmarg, pahalgam',
        'meta_canonical' => '',
        'offer' => 'Complimentary shikara ride'
    ],
    [
        'title' => 'Haridwar Rishikesh Tour Package',
        'slug' => 'haridwar-rishikesh-tour-package',
        'feature_image' => '',
        'duration' => '3 Nights / 4 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Haridwar, Rishikesh',
        'itinerary' => 'Day 1: Arrival in Haridwar. Day 2: Haridwar sightseeing. Day 3: Rishikesh excursion. Day 4: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Explore the spiritual towns of Haridwar and Rishikesh with our package.',
        'description' => 'Haridwar Rishikesh Tour Package is ideal for spiritual seekers and adventure lovers. Enjoy Ganga Aarti, yoga, and river rafting.',
        'is_active' => true,
        'meta_title' => 'Haridwar Rishikesh Tour Package',
        'meta_description' => 'Book Haridwar Rishikesh Tour Package for a spiritual and adventurous trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'haridwar, rishikesh, tour package, ganga aarti, yoga',
        'meta_canonical' => '',
        'offer' => 'Free yoga session'
    ],
    [
        'title' => 'Jammu City Tour Package',
        'slug' => 'jammu-city-tour-package',
        'feature_image' => '',
        'duration' => '2 Nights / 3 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Jammu city, temples, local markets',
        'itinerary' => 'Day 1: Arrival in Jammu. Day 2: City sightseeing. Day 3: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Discover the cultural heritage of Jammu with our city tour package.',
        'description' => 'Jammu City Tour Package covers major attractions, temples, and markets. Perfect for a short cultural trip.',
        'is_active' => true,
        'meta_title' => 'Jammu City Tour Package',
        'meta_description' => 'Book Jammu City Tour Package for a cultural trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'jammu, city tour, package, temples, markets',
        'meta_canonical' => '',
        'offer' => 'Free temple visit'
    ],
    [
        'title' => 'Srinagar Tour Package',
        'slug' => 'srinagar-tour-package',
        'feature_image' => '',
        'duration' => '3 Nights / 4 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Srinagar, Dal Lake, Mughal Gardens',
        'itinerary' => 'Day 1: Arrival in Srinagar. Day 2: Dal Lake and gardens. Day 3: Local sightseeing. Day 4: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Enjoy the beauty of Srinagar with our exclusive package.',
        'description' => 'Srinagar Tour Package offers scenic views, cultural experiences, and comfortable stays. Ideal for couples and families.',
        'is_active' => true,
        'meta_title' => 'Srinagar Tour Package',
        'meta_description' => 'Book Srinagar Tour Package for a memorable trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'srinagar, tour package, dal lake, mughal gardens',
        'meta_canonical' => '',
        'offer' => 'Complimentary garden entry'
    ],
    [
        'title' => 'Dharamshala Tour Package',
        'slug' => 'dharamshala-tour-package',
        'feature_image' => '',
        'duration' => '3 Nights / 4 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Dharamshala, McLeod Ganj',
        'itinerary' => 'Day 1: Arrival in Dharamshala. Day 2: McLeod Ganj sightseeing. Day 3: Local attractions. Day 4: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Explore the serene hills of Dharamshala and McLeod Ganj.',
        'description' => 'Dharamshala Tour Package is perfect for nature lovers and spiritual seekers. Enjoy peaceful surroundings and Tibetan culture.',
        'is_active' => true,
        'meta_title' => 'Dharamshala Tour Package',
        'meta_description' => 'Book Dharamshala Tour Package for a peaceful trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'dharamshala, tour package, mcleod ganj, tibetan culture',
        'meta_canonical' => '',
        'offer' => 'Free meditation session'
    ],
    [
        'title' => 'Kasol Tour Package',
        'slug' => 'kasol-tour-package',
        'feature_image' => '',
        'duration' => '2 Nights / 3 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Kasol, Parvati Valley',
        'itinerary' => 'Day 1: Arrival in Kasol. Day 2: Parvati Valley trek. Day 3: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Enjoy the hippie culture and scenic beauty of Kasol.',
        'description' => 'Kasol Tour Package is ideal for trekkers and nature lovers. Experience the unique vibe of Parvati Valley.',
        'is_active' => true,
        'meta_title' => 'Kasol Tour Package',
        'meta_description' => 'Book Kasol Tour Package for a scenic trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'kasol, tour package, parvati valley, trek',
        'meta_canonical' => '',
        'offer' => 'Free trekking guide'
    ],
    [
        'title' => 'Kullu Tour Package',
        'slug' => 'kullu-tour-package',
        'feature_image' => '',
        'duration' => '2 Nights / 3 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Kullu, local attractions',
        'itinerary' => 'Day 1: Arrival in Kullu. Day 2: Local sightseeing. Day 3: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Explore the beauty of Kullu with our package.',
        'description' => 'Kullu Tour Package is perfect for a short trip to the hills. Enjoy local attractions and comfortable stays.',
        'is_active' => true,
        'meta_title' => 'Kullu Tour Package',
        'meta_description' => 'Book Kullu Tour Package for a scenic trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'kullu, tour package, hills, sightseeing',
        'meta_canonical' => '',
        'offer' => 'Early booking discount'
    ],
    [
        'title' => 'Chandigarh Tour Package',
        'slug' => 'chandigarh-tour-package',
        'feature_image' => '',
        'duration' => '2 Nights / 3 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Chandigarh, Rock Garden, Sukhna Lake',
        'itinerary' => 'Day 1: Arrival in Chandigarh. Day 2: Rock Garden and Sukhna Lake. Day 3: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Discover the modern city of Chandigarh with our package.',
        'description' => 'Chandigarh Tour Package covers major attractions and offers comfortable stays. Perfect for families and couples.',
        'is_active' => true,
        'meta_title' => 'Chandigarh Tour Package',
        'meta_description' => 'Book Chandigarh Tour Package for a modern city trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'chandigarh, tour package, rock garden, sukhna lake',
        'meta_canonical' => '',
        'offer' => 'Free lake boat ride'
    ],
    [
        'title' => 'Amritsar Tour Package',
        'slug' => 'amritsar-tour-package',
        'feature_image' => '',
        'duration' => '2 Nights / 3 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Amritsar, Golden Temple, Jallianwala Bagh',
        'itinerary' => 'Day 1: Arrival in Amritsar. Day 2: Golden Temple and Jallianwala Bagh. Day 3: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Experience the spiritual and historical city of Amritsar.',
        'description' => 'Amritsar Tour Package covers major attractions and offers comfortable stays. Perfect for families and spiritual seekers.',
        'is_active' => true,
        'meta_title' => 'Amritsar Tour Package',
        'meta_description' => 'Book Amritsar Tour Package for a spiritual trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'amritsar, tour package, golden temple, jallianwala bagh',
        'meta_canonical' => '',
        'offer' => 'Free temple entry'
    ],
    [
        'title' => 'Haridwar Tour Package',
        'slug' => 'haridwar-tour-package',
        'feature_image' => '',
        'duration' => '2 Nights / 3 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Haridwar, Ganga Aarti',
        'itinerary' => 'Day 1: Arrival in Haridwar. Day 2: Ganga Aarti and sightseeing. Day 3: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Experience the spiritual city of Haridwar with our package.',
        'description' => 'Haridwar Tour Package is ideal for spiritual seekers. Enjoy Ganga Aarti and comfortable stays.',
        'is_active' => true,
        'meta_title' => 'Haridwar Tour Package',
        'meta_description' => 'Book Haridwar Tour Package for a spiritual trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'haridwar, tour package, ganga aarti, spiritual',
        'meta_canonical' => '',
        'offer' => 'Free Ganga Aarti experience'
    ],
    [
        'title' => 'Rishikesh Tour Package',
        'slug' => 'rishikesh-tour-package',
        'feature_image' => '',
        'duration' => '2 Nights / 3 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Rishikesh, yoga, river rafting',
        'itinerary' => 'Day 1: Arrival in Rishikesh. Day 2: Yoga and river rafting. Day 3: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Enjoy adventure and spirituality in Rishikesh.',
        'description' => 'Rishikesh Tour Package is perfect for adventure lovers and spiritual seekers. Experience yoga, river rafting, and comfortable stays.',
        'is_active' => true,
        'meta_title' => 'Rishikesh Tour Package',
        'meta_description' => 'Book Rishikesh Tour Package for an adventurous trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'rishikesh, tour package, yoga, river rafting',
        'meta_canonical' => '',
        'offer' => 'Free yoga session'
    ],
    [
        'title' => 'Nainital Tour Package',
        'slug' => 'nainital-tour-package',
        'feature_image' => '',
        'duration' => '3 Nights / 4 Days',
        'amenities' => json_encode(['AC Cab', 'Hotel', 'Meals', 'Sightseeing']),
        'highlights' => 'Nainital, lakes, local attractions',
        'itinerary' => 'Day 1: Arrival in Nainital. Day 2: Lake tour. Day 3: Local sightseeing. Day 4: Departure.',
        'included' => 'Accommodation, transport, breakfast, sightseeing',
        'excluded' => 'Lunch, personal expenses, adventure activities',
        'more_contents' => 'Explore the lakes and hills of Nainital with our package.',
        'description' => 'Nainital Tour Package is ideal for families and couples. Enjoy lake tours, local attractions, and comfortable stays.',
        'is_active' => true,
        'meta_title' => 'Nainital Tour Package',
        'meta_description' => 'Book Nainital Tour Package for a scenic trip. Best deals, top amenities, and expert guides.',
        'meta_keywords' => 'nainital, tour package, lakes, sightseeing',
        'meta_canonical' => '',
        'offer' => 'Free lake boat ride'
    ],
    [
        'title' => 'Airport Taxi in Gurgaon',
        'slug' => 'airport-taxi-in-gurgaon',
        'feature_image' => '',
        'duration' => '',
        'amenities' => json_encode(['AC Cab', 'On-Time Service']),
        'highlights' => 'Airport transfers, punctuality',
        'itinerary' => '',
        'included' => 'Cab, driver, airport transfer',
        'excluded' => 'Waiting charges, tolls',
        'more_contents' => 'Trusted airport taxi service in Gurgaon for timely and safe transfers.',
        'description' => 'Airport Taxi in Gurgaon offers reliable and punctual cab service for airport transfers. Book for trusted and comfortable rides.',
        'is_active' => true,
        'meta_title' => 'Airport Taxi in Gurgaon',
        'meta_description' => 'Book Airport Taxi in Gurgaon for trusted and on-time cab service.',
        'meta_keywords' => 'airport taxi, gurgaon, cab service',
        'meta_canonical' => '',
        'offer' => 'Flat Rs. 200 off on first booking'
    ],
    [
        'title' => 'Airport Taxi in Gurgaon - Trusted & On-Time Cab Service',
        'slug' => 'airport-taxi-in-gurgaon-trusted-on-time-cab-service',
        'feature_image' => '',
        'duration' => '',
        'amenities' => json_encode(['AC Cab', 'On-Time Service']),
        'highlights' => 'Airport transfers, punctuality',
        'itinerary' => '',
        'included' => 'Cab, driver, airport transfer',
        'excluded' => 'Waiting charges, tolls',
        'more_contents' => 'Trusted airport taxi service in Gurgaon for timely and safe transfers.',
        'description' => 'Airport Taxi in Gurgaon offers reliable and punctual cab service for airport transfers. Book for trusted and comfortable rides.',
        'is_active' => true,
        'meta_title' => 'Airport Taxi in Gurgaon - Trusted & On-Time Cab Service',
        'meta_description' => 'Book Airport Taxi in Gurgaon for trusted and on-time cab service.',
        'meta_keywords' => 'airport taxi, gurgaon, cab service',
        'meta_canonical' => '',
        'offer' => 'Flat Rs. 200 off on first booking'
    ],
    [
        'title' => 'Outstation Cab Service In Gurgaon Cab',
        'slug' => 'outstation-cab-service-in-gurgaon-cab',
        'feature_image' => '',
        'duration' => '',
        'amenities' => json_encode(['AC Cab', 'Outstation Service']),
        'highlights' => 'Outstation trips, comfort',
        'itinerary' => '',
        'included' => 'Cab, driver, outstation transfer',
        'excluded' => 'Waiting charges, tolls',
        'more_contents' => 'Book outstation cab service in Gurgaon for comfortable and safe journeys.',
        'description' => 'Outstation Cab Service in Gurgaon offers reliable and comfortable cab service for outstation trips. Book for trusted and safe rides.',
        'is_active' => true,
        'meta_title' => 'Outstation Cab Service In Gurgaon Cab',
        'meta_description' => 'Book Outstation Cab Service in Gurgaon for trusted and comfortable rides.',
        'meta_keywords' => 'outstation cab, gurgaon, cab service',
        'meta_canonical' => '',
        'offer' => 'Flat Rs. 300 off on first booking'
    ],
    [
        'title' => 'Car Rental in gurgaon trusted cabs for every trip',
        'slug' => 'car-rental-in-gurgaon-trusted-cabs-for-every-trip',
        'feature_image' => '',
        'duration' => '',
        'amenities' => json_encode(['AC Cab', 'Car Rental']),
        'highlights' => 'Car rental, trusted service',
        'itinerary' => '',
        'included' => 'Cab, driver, car rental',
        'excluded' => 'Waiting charges, tolls',
        'more_contents' => 'Book car rental in Gurgaon for trusted cabs for every trip.',
        'description' => 'Car Rental in Gurgaon offers reliable and trusted cab service for all your travel needs. Book for comfortable and safe rides.',
        'is_active' => true,
        'meta_title' => 'Car Rental in gurgaon trusted cabs for every trip',
        'meta_description' => 'Book Car Rental in Gurgaon for trusted cabs for every trip.',
        'meta_keywords' => 'car rental, gurgaon, cab service',
        'meta_canonical' => '',
        'offer' => 'Flat Rs. 250 off on first booking'
    ]
];

foreach ($packages as $data) {
    Service::create($data);
}
